### ISSUE TITLE
Handle uncaught panics

### ISSUE THREAD

**Issue by ribice** [getsentry/sentry-go#881] opened 2024-09-04 11:03 UTC
As a Sentry user, I want to capture and report uncaught panics, including stack traces, to Sentry.

This requires an additional process or binary that monitors for these panics and ensures proper reporting to Sentry upon application exit.

**Comment by cleptric** [comment] 2024-12-06 12:24
Duplicate of https://github.com/getsentry/sentry-go/issues/107

**Closed by cleptric** 2024-12-06 12:24 UTC
Labels: Type: Feature
