### ISSUE TITLE
Exception is not fire in dashboard, using sentry-go and gin

### ISSUE THREAD

**Issue by dmitry-pirate** [getsentry/sentry-go#275] opened 2020-09-09 10:03 UTC
## Summary
I’m creating microservices on golang/gin and I want to track my exceptions. I’m use docs [Gin Docs](https://docs.sentry.io/platforms/go/guides/gin/), but exceptions is not visible on dashboard. I debugged the message and it is being sent, also in sentry debug I received:
[Sentry] 2020/08/12 15:25:05 Sending error event [id here] to url project: project id
Project id is correct. Any idea?

### Init
```go
func (a *App) configureLogger() error {
	return sentry.Init(sentry.ClientOptions{
		Dsn:              a.config.Logger.DSN,
		Debug:            a.config.Server.Env != "production",
		Environment:      a.config.Server.Env,
		AttachStacktrace: true,
	})
}
```

### Helper
```go
//CaptureException fire exception to sentry with user ip only
func CaptureException(c *gin.Context, err error) *sentry.EventID {
	userIP := c.GetHeader("Cf-Connecting-Ip")
	if hub := sentrygin.GetHubFromContext(c); hub != nil {
		var id *sentry.EventID
		hub.WithScope(func(scope *sentry.Scope) {
			hub.Scope().SetUser(sentry.User{
				IPAddress: userIP,
			})
			id = hub.CaptureException(err)
		})
		return id
	}
	return nil
}
```

### Catch
```go
if err := c.Bind(request); err != nil {
			id := logger.CaptureException(c, err)
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{
				"success": false,
				"id":      id,
				"msg":     "Internal server error. Please log out and log in again.",
			})
			return
		}
```

### Router config
```go
func (a *App) configureRouter() {
	v1 := a.router.Group("/")
	{
		v1.Use(sentrygin.New(sentrygin.Options{
			Repanic: true,
		}))
		some code here...
	}
}
```

## Expected Behavior
Event list on my sentry dashboard

## Screenshots
![2020-09-09_13-06](https://user-images.githubusercontent.com/11944357/92585199-50f14d80-f29d-11ea-8832-fa15c7ed5288.png)

## Environment
development and production

### SDK
 - `sentry-go` version: `v0.7.0`
 - Go version: `1.14`
 - Using Go Modules? `yes`

### Sentry
 - Using hosted Sentry in sentry.io? `no`
 - Using your own Sentry installation? Version: 
 - Anything particular to your environment that could be related to this issue? `no`

**Comment by rhcarvalho** [comment] 2020-09-09 13:34
@dmitry-pirate if you're not using `sentry.io` what version of Sentry are you hosting? This sounds like a configuration problem.

**Comment by dmitry-pirate** [comment] 2020-09-10 07:32
@rhcarvalho thx for answer, my version sentry: `version 9.1.0.dev0 (2c328eae6157)`

**Comment by rhcarvalho** [comment] 2020-09-10 12:14
Unfortunately I don't have the capacity to help you debug your own Sentry server instance more than suggest you or your Sentry admin to look at the documentation from your Sentry version for debugging event ingestion, making sure to check logs and project settings that cause events to be filtered out, and perhaps look at network traffic.

[Sentry@2c328eae6157](https://github.com/getsentry/sentry/commits/2c328eae6157) is from March 2019. One thing we can always recommend is to upgrade to a more recent server version if that's within your reach, or [migrate to our hosted solution](https://docs.sentry.io/product/sentry-basics/guides/migration/). We have a free tier and are constantly landing improvements and new features. If `sentry-go` doesn't work for you with sentry.io we'd have better means to help.

Other than that, you can also look for community support at https://forum.sentry.io.

Closing for now as this seems to be unrelated to the Go SDK and irreproducible.

**Closed by rhcarvalho** 2020-09-10 12:14 UTC
Labels: Type: Question
