### ISSUE TITLE
client.CaptureEvent returns EventID regardless of request outcome to Sentry.io

### ISSUE THREAD

**Issue by ArcticSnowman** [getsentry/sentry-go#475] opened 2022-09-29 16:29 UTC
## Summary
According to the documentation, the client.CaptureEvent is 

> The return value is the event ID. In case Sentry is disabled or event was dropped, the return value will be nil.

However the return is only NIL when the sentry is disabled in the client or the sampling rate drops the message.
The ClientID will always be returned regardless of the outcome of the request to sentry.io.

At the very least the documentation should be update to clarify that the return of a nill EventID does not determine if the event made it to sentry.io or was ingested or dropped by sentry.io

**Comment by cleptric** [comment] 2022-10-30 23:37
Duplicate of https://github.com/getsentry/sentry-go/issues/174

**Closed by cleptric** 2022-10-30 23:37 UTC
Labels: Type: Documentation
