### ISSUE TITLE
remove other dependency

### ISSUE THREAD

**Issue by hidu** [getsentry/sentry-go#405] opened 2021-12-24 10:45 UTC
## Summary

A basic SDK should have the least dependence.
But in go.mod, it requred too many other pkgs, these should be reduced.
eg:
```
github.com/gin-gonic/gin v1.4.0
github.com/kataras/iris/v12 v12.1.8
github.com/labstack/echo/v4 v4.5.0
...
```
these adapters should in a separate module

**Comment by rhcarvalho** [comment] 2022-01-12 12:26
Closing as a duplicate of #156.

**Closed by rhcarvalho** 2022-01-12 12:26 UTC
Labels: Type: Feature
