### ISSUE TITLE
Ability to skip certain callstack

### ISSUE THREAD

**Issue by kokizzu** [getsentry/sentry-go#424] opened 2022-03-15 20:00 UTC
## Summary
Use case:
```
// usage
defer LogPanic(time.Now(), identity)
panic(`foo`)

// function
func LogPanic(start time.Time, ident string)  {
   err := recover() 
   if err != nil {
        // log, increment metric, send to slack, etc
	sentry.CurrentHub().WithScope(func(scope *sentry.Scope) {
		scope.SetLevel(sentry.LevelFatal)
		sentry.CaptureMessage(fmt.Sprint(err))
	})
   }
}
```

## Motivation
if we want to do something else with the `recover` it always show LogPanic as the source of the problem instead of real panic(`foo`)

## Additional Context
it would be ok if it can skip specific number of stacktrace, eg. `sentry.CaptureMessageWithStackSkip(err, 2)` // skip 2 callstack

**Comment by kamilogorek** [comment] 2022-03-16 10:17
Duplicate of #395. Also, here's discussion on how you can achieve it right now: https://github.com/getsentry/sentry-go/issues/395#issuecomment-1050927901

**Closed by kamilogorek** 2022-03-16 10:17 UTC
Labels: Type: Feature
