### ISSUE TITLE
Provide a `slog` handler

### ISSUE THREAD

**Issue by flimzy** [getsentry/sentry-go#708] opened 2023-09-01 09:36 UTC
## Summary
Now that `log/slog` has landed in the standard library, it would be nice to provide an official Sentry handler.  There are third-party handlers available (https://github.com/samber/slog-sentry as an example), but having one in this repo that tracks with new features, and corresponds to the existing handlers for other logging systems would make sense to me.

I'm also happy to work on the implementation, if the core team doesn't have the time/resources.

**Comment by cleptric** [comment] 2023-09-01 10:06
Closing as a duplicate of https://github.com/getsentry/sentry-go/issues/527.

In any case, PRs are always welcome 😃

**Closed by cleptric** 2023-09-01 10:06 UTC
Labels: Type: Feature
