### ISSUE TITLE
Dependencies conflict while updates the sentry version to 0.3.1

### ISSUE THREAD

**Issue by d0sdoc** [getsentry/sentry-go#87] opened 2019-11-15 11:11 UTC
Hello everyone, 
I've tried to update the sentry-go version to 0.3.1 and got an error:
```
build app: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```

I've changed in go.mod of my project `github.com/getsentry/sentry-go v0.3.0` to `github.com/getsentry/sentry-go v0.3.1`

Here are the ugorji entries in go.sum:
```
github.com/ugorji/go v1.1.1/go.mod h1:hnLbHMwcvSihnDhEfx2/BzKp2xb0Y+ErdfYcrs9tkJQ=
github.com/ugorji/go v1.1.4 h1:j4s+tAvLfL3bZyefP2SEWmhBzmuIlH/eqNuPdFPgngw=
github.com/ugorji/go v1.1.4/go.mod h1:uQMGLiO92mf5W77hV/PUCpI3pbzQx3CRekS0kk+RGrc=
github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 h1:3SVOIvH7Ae1KRYyQWRjXWJEA9sS/c/pjvH++55Gr648=
github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8/go.mod h1:VFNgLljTbGfSG7qAOspJ7OScBnGdDN/yBr0sguwnwf0=
```

go version is 1.13

**Comment by kamilogorek** [comment] 2019-11-15 11:46
This addition to `go.mod` should fix it:
```
replace github.com/ugorji/go v1.1.4 => github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43
```
from: https://github.com/getsentry/sentry-go/blob/master/go.mod

Although I thought it should be propagated to all the packages relaying on our go.mod :|
I'll try to sort this + https://github.com/getsentry/sentry-go/issues/75#issuecomment-553648455 next week.

**Comment by rhcarvalho** [comment] 2019-12-05 16:05
For the record, I just realized this is one of those cases of multiple modules in one repo.

---

@kamilogorek like we were discussing in https://github.com/getsentry/sentry-go/issues/79

https://github.com/ugorji/go/blob/master/go.mod
https://github.com/ugorji/go/blob/master/codec/go.mod

**Comment by rhcarvalho** [comment] 2019-12-05 16:09
> Although I thought it should be propagated to all the packages relaying on our go.mod :|

@kamilogorek

https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
"replace directives in modules other than the main module are ignored when building the main module"

We should not need to have a `replace` directive in sentry-go, because we are a library and not the main module. Let's see if we can get rid of that replace...

**Comment by rhcarvalho** [comment] 2019-12-05 17:05
Hi @d0sdoc do you still need any help? Were you able to fix the problem?

The only thing in `sentry-go` that pulls in `github.com/ugorji/go/codec` is the integration with `github.com/gin-gonic/gin`. Are you using `gin` in your program? What version?

```
go list -m github.com/gin-gonic/gin
```

---

I wrote a test program using Go modules and sentry-go v0.3.1 and gin v1.4.0 (the minimum required by sentry-go@v0.3.1) and could no reproduce the issue.

```
$ cat main.go
package main

import (
        "fmt"

        "github.com/getsentry/sentry-go"
        "github.com/gin-gonic/gin"
)

func main() {
        sentry.Init(sentry.ClientOptions{Debug: true})
        fmt.Println("hello", gin.BodyBytesKey)
}
$ go list -m github.com/gin-gonic/gin github.com/getsentry/sentry-go
github.com/gin-gonic/gin v1.4.0
github.com/getsentry/sentry-go v0.3.1
$ go version
go version go1.13.4 darwin/amd64
```

---

Please let me know if you have a repro or otherwise we can close this.

Thank you!

**Comment by rhcarvalho** [comment] 2019-12-05 17:16
Reference to issue in gin: https://github.com/gin-gonic/gin/issues/1673
And in ugorji/go: https://github.com/ugorji/go/issues/279, https://github.com/ugorji/go/issues/299

**Comment by rhcarvalho** [comment] 2019-12-05 17:47
Okay, I found out why I could not reproduce the issue.

When installing dependencies on a clean, new, module I got a newer version of `github.com/ugorji/go` that has a fix for the inconsistency @d0sdoc observed.

```
module example

go 1.13

require (
	github.com/getsentry/sentry-go v0.3.1
	github.com/gin-gonic/gin v1.4.0
	github.com/golang/protobuf v1.3.2 // indirect
	github.com/json-iterator/go v1.1.8 // indirect
	github.com/ugorji/go v1.1.7 // indirect            <--------
	gopkg.in/yaml.v2 v2.2.7 // indirect
)
```

Removing the line marked above, or downgrading `github.com/ugorji/go` reproduces the original issue.

@d0sdoc apart from the `replace` directive suggested earlier, another solution I can propose is to bump the version of `github.com/ugorji/go` in your project:

```
go get -u github.com/ugorji/go@v1.1.7
```

AFAICT that is the cleanest fix.

**Comment by d0sdoc** [comment] 2019-12-06 03:26
> Hi @d0sdoc do you still need any help? Were you able to fix the problem?
> 
> The only thing in `sentry-go` that pulls in `github.com/ugorji/go/codec` is the integration with `github.com/gin-gonic/gin`. Are you using `gin` in your program? What version?
> 
> ```
> go list -m github.com/gin-gonic/gin
> ```
> 
> I wrote a test program using Go modules and sentry-go v0.3.1 and gin v1.4.0 (the minimum required by sentry-go@v0.3.1) and could no reproduce the issue.
> 
> ```
> $ cat main.go
> package main
> 
> import (
>         "fmt"
> 
>         "github.com/getsentry/sentry-go"
>         "github.com/gin-gonic/gin"
> )
> 
> func main() {
>         sentry.Init(sentry.ClientOptions{Debug: true})
>         fmt.Println("hello", gin.BodyBytesKey)
> }
> $ go list -m github.com/gin-gonic/gin github.com/getsentry/sentry-go
> github.com/gin-gonic/gin v1.4.0
> github.com/getsentry/sentry-go v0.3.1
> $ go version
> go version go1.13.4 darwin/amd64
> ```
> 
> Please let me know if you have a repro or otherwise we can close this.
> 
> Thank you!

Yes, I'm using gin, version 1.4.0.

I've bump the ugorji version and it works, I've put ```github.com/ugorji/go v1.1.7``` into go.mod.

**Closed** 2019-12-11 22:39 UTC
Labels: Status: Confirmed, Status: Needs Information, Type: Bug
