### ISSUE TITLE
Golang client child-spans are reported as the root span and child spans at the same time

### ISSUE THREAD

**Issue by deepblue-phoenix** [getsentry/sentry-go#324] opened 2021-01-17 06:58 UTC
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

using Sentry tracing spans in a net/http handler. creating 2 spans, one parent (root handler level), and one child span that uses the context of the parent span.
when investigating tracing details in the "Performance" section of the Sentry dashboard, the root span is marked as the child of the child-span. the child-span is booth the root and the child, and yet has the same span ID.

## Steps to Reproduce

         http.HandleFunc("/test", func(p_resp http.ResponseWriter, p_req *http.Request) {
		
		ctx := p_req.Context()

		span__root := sentry.StartSpan(ctx, "1111111111")
		time.Sleep(2 * time.Second)
		span__root.Finish()

		span__222 := sentry.StartSpan(span__root.Context(), "2222222222222222")
		time.Sleep(2 * time.Second)
		span__222.Finish()
	})

![image](https://user-images.githubusercontent.com/477476/104833511-36d90480-5867-11eb-8d67-2ad320819258.png)

expectation is for the span "11111111111" to be at the root of the span tree, and "222222222222222222" to be the child and only included once.

**Comment by deepblue-phoenix** [comment] 2021-01-22 00:49
@rhcarvalho could you point me to where this issue is residing right now, so I can keep an eye on it. I would really like to make some progress in resolving this. The solution is not obvious from the current Sentry Go documentation thats accessible.

**Comment by kamilogorek** [comment] 2021-01-22 10:37
Can you provide the same screenshot with all the span details visible?

In case of:
```
| root
| -- childA
|     | -- grandchildA
| -- child B
|     | -- grandchildB
```

- All 5 spans should have _the same_ TracingID
- All 5 spans should have _unique_ SpanID
- `childA` and `childB` should have `ParentID` equal to `SpanID` of `root`
- `grandchildA` should have `ParentID` equal to `SpanID` of `childA`
- `grandchildB` should have `ParentID` equal to `SpanID` of `childB`

Implementation is done here: https://github.com/getsentry/sentry-go/blob/master/tracing.go#L77-L154

**Comment by compleatang** [comment] 2021-02-03 01:24
I'm running into this as well. I've crafted a relatively arbitrary test to see if I could help with debugging. 

Here's the "zoomed out" view within Sentry:

![screenshot-sentry io-2021 02 03-00_53_01](https://user-images.githubusercontent.com/590037/106682620-d19d4700-65ba-11eb-93a4-cd1320d24d7e.png)

Here's the "zoomed in" view within Sentry:

![screenshot-sentry io-2021 02 03-00_52_17](https://user-images.githubusercontent.com/590037/106682647-dfeb6300-65ba-11eb-9ab6-1a3d0e15abf2.png)

I've logged the code around the spans within my core function and this is the output I'm seeing at the code level:

```
msg=root component=scalia span="&{TraceID:931740f5d3de45daa8456569c9a72c0e SpanID:c20b8e2e25714cc5 ParentSpanID:842566fbbca6ba30 Op:scalia.assemble Description: Status: Tags:map[] StartTime:2021-02-03 00:50:27.567908537 +0000 UTC m=+6.784867083 EndTime:0001-01-01 00:00:00 +0000 UTC Data:map[] Sampled:SampledTrue ctx:0xc00036ff80 parent:<nil> isTransaction:true recorder:0xc00027c060}"
msg=prepare component=scalia span="&{TraceID:931740f5d3de45daa8456569c9a72c0e SpanID:b3c7c55cf4743834 ParentSpanID:c20b8e2e25714cc5 Op:prepare document Description: Status: Tags:map[] StartTime:2021-02-03 00:50:27.567989079 +0000 UTC m=+6.784947625 EndTime:2021-02-03 00:50:27.569740502 +0000 UTC m=+6.786699048 Data:map[] Sampled:SampledTrue ctx:0xc00027c090 parent:0xc00052c300 isTransaction:false recorder:0xc00027c060}"
msg=assemble component=scalia span="&{TraceID:931740f5d3de45daa8456569c9a72c0e SpanID:34e0fde64d1c17af ParentSpanID:b3c7c55cf4743834 Op:assemble document Description: Status: Tags:map[] StartTime:2021-02-03 00:50:27.569979063 +0000 UTC m=+6.786937589 EndTime:2021-02-03 00:50:27.613988046 +0000 UTC m=+6.830946572 Data:map[] Sampled:SampledTrue ctx:0xc000810600 parent:0xc00052c3c0 isTransaction:false recorder:0xc00027c060}"
msg=finalize component=scalia span="&{TraceID:931740f5d3de45daa8456569c9a72c0e SpanID:59d5d393817ba4c8 ParentSpanID:34e0fde64d1c17af Op:finalize document with gotenberg Description: Status: Tags:map[] StartTime:2021-02-03 00:50:27.614062466 +0000 UTC m=+6.831020972 EndTime:2021-02-03 00:50:29.019750479 +0000 UTC m=+8.236708985 Data:map[] Sampled:SampledTrue ctx:0xc0005a1920 parent:0xc0000ba480 isTransaction:false recorder:0xc00027c060}"
```

I also dumped the spans from a simple global event processor and here are the results (note there are only three and not four, but I'm not sure if the "root span" counts as a span or not). 

```
msg=processor component=scalia event="&{TraceID:2bc3d60c49a04b2fb5ab4e97236b7412 SpanID:ff0a3d3749243a4f ParentSpanID:1537bc07c3fdd32d Op:prepare document Description: Status: Tags:map[] StartTime:2021-02-03 01:03:14.96342243 +0000 UTC m=+6.293321867 EndTime:2021-02-03 01:03:14.9647537 +0000 UTC m=+6.294653137 Data:map[] Sampled:SampledTrue ctx:0xc0007112c0 parent:0xc000494240 isTransaction:false recorder:0xc000711290}"
msg=processor component=scalia event="&{TraceID:2bc3d60c49a04b2fb5ab4e97236b7412 SpanID:b3370d3cb72c9160 ParentSpanID:ff0a3d3749243a4f Op:assemble document Description: Status: Tags:map[] StartTime:2021-02-03 01:03:14.965354777 +0000 UTC m=+6.295255076 EndTime:2021-02-03 01:03:15.010833201 +0000 UTC m=+6.340733500 Data:map[] Sampled:SampledTrue ctx:0xc00011a1b0 parent:0xc000494300 isTransaction:false recorder:0xc000711290}"
msg=processor component=scalia event="&{TraceID:2bc3d60c49a04b2fb5ab4e97236b7412 SpanID:88154737702145b3 ParentSpanID:b3370d3cb72c9160 Op:finalize document with gotenberg Description: Status: Tags:map[] StartTime:2021-02-03 01:03:15.010947869 +0000 UTC m=+6.340847306 EndTime:2021-02-03 01:03:16.46327409 +0000 UTC m=+7.793173527 Data:map[] Sampled:SampledTrue ctx:0xc000473920 parent:0xc0001c06c0 isTransaction:false recorder:0xc000711290}"
```

Finally, here is a redacted version of the entire transaction from the global event processor's point of view:

```
msg=processor component=scalia event="&{Breadcrumbs:[] Contexts:map[] Dist: Environment: EventID:aa4de52a5ec54bc1972018a23d32db02 Extra:map[] Fingerprint:[] Level:info Message: Platform:go Release:v Sdk:{Name:sentry.go Version:0.9.0 Integrations:[ContextifyFrames Environment IgnoreErrors Modules] Packages:[{Name:sentry-go Version:0.9.0}]} ServerName:408c5a3b04ba Threads:[] Tags:map[] Timestamp:2021-02-03 01:06:51.063361786 +0000 UTC m=+7.328572145 Transaction:Assembling documents User:{Email: ID: IPAddress: Username:} Logger: Modules:map[] Request:<nil> Exception:[] Type:transaction StartTime:2021-02-03 01:06:49.591143721 +0000 UTC m=+5.856354080 Spans:[0xc00013a480 0xc00013a900 0xc000671200]}"
```

One final point of note here is that the above is triggered via GRPC so I would expect Request to be nil (as it is).

Since the `spanRecorder` isn't exported I was unable to fully recomprise something like the `TestStartChild` test

**Comment by compleatang** [comment] 2021-02-03 01:36
FWIW, this issue appears a dupe // same root cause as #311 and #318

**Comment by deepblue-phoenix** [comment] 2021-02-03 02:57
good find @compleatang! glad this is reproducible by multiple people.

**Comment by deepblue-phoenix** [comment] 2021-02-10 02:07
any updates on this issue? I see that its somewhat common so I was wondering if there are clues and thoughts on how to mitigate.
thank you for any guidance :)

**Comment by rhcarvalho** [comment] 2021-02-10 09:16
@deepblue-phoenix for personal reasons I was not able to work on this yet. We should have a solution by the end of the week.

**Comment by gloflow** [comment] 2021-02-10 15:13
thats great news @rhcarvalho! I hope you're ok, definitely take the time you need to take care of yourself. 
keep us posted. excited to get this to work :)

**Comment by deepblue-phoenix** [comment] 2021-02-10 15:14
thats great news @rhcarvalho! I hope you're ok, definitely take the time you need to take care of yourself.
keep us posted. excited to get this to work (smiley)

**Comment by hlubek** [comment] 2021-02-11 17:15
I also expected that it works like described on https://docs.sentry.io/platforms/go/guides/http/performance/custom-instrumentation/ and faced the same / similiar issue when adding a span inside a request using the `sentryhttp.New(sentryhttp.Options{})` middleware (which creates a root span).

What seems to work is the following workaround:

```
func myNestedOp(ctx context.Context) {
	sentryHub := sentry.GetHubFromContext(ctx)
	sentryHub.PushScope()
	defer sentryHub.PopScope()

	span := sentry.StartSpan(ctx, "my.nested.op", sentry.TransactionName("Do something"))
	defer span.Finish()

	// actual work
}
```

**Comment by rhcarvalho** [comment] 2021-02-14 00:06
Closing this as a duplicate of #318. There are a few fixes to be merged and released early in the week. Sorry for the delay.

**Closed by rhcarvalho** 2021-02-14 00:06 UTC
